USE [master]
GO
/****** Objeto:  Database [study_management]    Data do Script: 19/05/2026 16:29:58 ******/
CREATE DATABASE [study_management]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'study_management', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\study_management.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'study_management_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\study_management_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [study_management] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [study_management].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [study_management] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [study_management] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [study_management] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [study_management] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [study_management] SET ARITHABORT OFF 
GO
ALTER DATABASE [study_management] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [study_management] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [study_management] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [study_management] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [study_management] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [study_management] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [study_management] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [study_management] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [study_management] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [study_management] SET  ENABLE_BROKER 
GO
ALTER DATABASE [study_management] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [study_management] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [study_management] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [study_management] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [study_management] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [study_management] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [study_management] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [study_management] SET RECOVERY FULL 
GO
ALTER DATABASE [study_management] SET  MULTI_USER 
GO
ALTER DATABASE [study_management] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [study_management] SET DB_CHAINING OFF 
GO
ALTER DATABASE [study_management] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [study_management] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [study_management] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [study_management] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [study_management] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [study_management] SET QUERY_STORE = ON
GO
ALTER DATABASE [study_management] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [study_management]
GO
/****** Objeto:  Table [dbo].[goals]    Data do Script: 19/05/2026 16:29:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[goals](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[title] [varchar](100) NOT NULL,
	[progress] [int] NULL,
	[objective_hours] [decimal](5, 2) NOT NULL,
	[start_date_goal] [datetime] NULL,
	[end_date_goal] [datetime] NULL,
	[user_id] [int] NULL,
	[subject_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto:  Table [dbo].[study_sessions]    Data do Script: 19/05/2026 16:29:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[study_sessions](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[duration] [int] NOT NULL,
	[session_date] [datetime] NULL,
	[observations] [varchar](max) NULL,
	[subject_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto:  Table [dbo].[subjects]    Data do Script: 19/05/2026 16:29:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[subjects](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[subject_name] [varchar](200) NOT NULL,
	[subject_description] [varchar](max) NULL,
	[color] [varchar](100) NULL,
	[user_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto:  Table [dbo].[users]    Data do Script: 19/05/2026 16:29:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name_user] [varchar](200) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[password_user] [varchar](255) NOT NULL,
	[creation_date] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_users_email] UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[goals] ADD  DEFAULT (getdate()) FOR [start_date_goal]
GO
ALTER TABLE [dbo].[study_sessions] ADD  DEFAULT (getdate()) FOR [session_date]
GO
ALTER TABLE [dbo].[users] ADD  DEFAULT (getdate()) FOR [creation_date]
GO
ALTER TABLE [dbo].[goals]  WITH CHECK ADD  CONSTRAINT [FK_goal_materia] FOREIGN KEY([subject_id])
REFERENCES [dbo].[subjects] ([id])
GO
ALTER TABLE [dbo].[goals] CHECK CONSTRAINT [FK_goal_materia]
GO
ALTER TABLE [dbo].[goals]  WITH CHECK ADD  CONSTRAINT [FK_goal_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([id])
GO
ALTER TABLE [dbo].[goals] CHECK CONSTRAINT [FK_goal_user]
GO
ALTER TABLE [dbo].[study_sessions]  WITH CHECK ADD  CONSTRAINT [FK_session_materia] FOREIGN KEY([subject_id])
REFERENCES [dbo].[subjects] ([id])
GO
ALTER TABLE [dbo].[study_sessions] CHECK CONSTRAINT [FK_session_materia]
GO
ALTER TABLE [dbo].[subjects]  WITH CHECK ADD  CONSTRAINT [FK_materia_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([id])
GO
ALTER TABLE [dbo].[subjects] CHECK CONSTRAINT [FK_materia_user]
GO
USE [master]
GO
ALTER DATABASE [study_management] SET  READ_WRITE 
GO
